import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import storyRoutes from "./story.routes";
import characterRoutes from "./character.routes";
import chapterRoutes from "./chapter.routes";
import sceneRoutes from "./scene.routes";
import contributionRoutes from "./contribution.routes";
import participantRoutes from "./participant.routes";
import joinRequestRoutes from "./joinRequest.routes";
import activityRoutes from "./activity.routes";
import devRoutes from "./dev.routes";
import battleRoutes from "./battle.routes";
import reportRoutes from "./report.routes";
import adminRoutes from "./admin.routes";
import notificationRoutes from "./notification.routes";
import aiRoutes from "./ai.routes";
import worldRoutes from "./world.routes";

const router = Router();

router.use(authRoutes);
router.use(userRoutes);
router.use(storyRoutes);
router.use(characterRoutes);
router.use(chapterRoutes);
router.use(sceneRoutes);
router.use(contributionRoutes);
router.use(participantRoutes);
router.use(joinRequestRoutes);
router.use(activityRoutes);
router.use(devRoutes);
router.use(battleRoutes);
router.use(reportRoutes);
router.use(adminRoutes);
router.use(notificationRoutes);
router.use(aiRoutes);
router.use(worldRoutes);

export default router;
